"""init schema

Revision ID: 9653f23751e6
Revises: 
Create Date: 2026-01-31 11:07:47.387984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9653f23751e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_bins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('fill_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('waste_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('visual_conf', sa.Float(), nullable=True),
    sa.Column('audio_conf', sa.Float(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bin_id'], ['smart_bins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomaly_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waste_log_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('user_label', sa.String(length=50), nullable=True),
    sa.Column('status_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['waste_log_id'], ['waste_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carbon_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('co2_reduction_value', sa.Float(), nullable=False),
    sa.Column('methane_reduction', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['waste_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carbon_metrics')
    op.drop_table('anomaly_data')
    op.drop_table('waste_logs')
    op.drop_table('users')
    op.drop_table('smart_bins')
    # ### end Alembic commands ###
